export const TAROT_DECK=[
{name:"The Fool",num:"0",suit:"major",meaning:"New beginnings, innocence, free spirit"},
{name:"The Magician",num:"I",suit:"major",meaning:"Willpower, skill, manifestation"},
{name:"The High Priestess",num:"II",suit:"major",meaning:"Intuition, mystery, inner wisdom"},
{name:"The Empress",num:"III",suit:"major",meaning:"Abundance, nature, creativity"},
{name:"The Emperor",num:"IV",suit:"major",meaning:"Authority, structure, leadership"},
{name:"The Hierophant",num:"V",suit:"major",meaning:"Tradition, spiritual guidance, wisdom"},
{name:"The Lovers",num:"VI",suit:"major",meaning:"Love, harmony, choices"},
{name:"The Chariot",num:"VII",suit:"major",meaning:"Victory, determination, willpower"},
{name:"Strength",num:"VIII",suit:"major",meaning:"Inner strength, courage, patience"},
{name:"The Hermit",num:"IX",suit:"major",meaning:"Soul searching, solitude, inner wisdom"},
{name:"Wheel of Fortune",num:"X",suit:"major",meaning:"Fate, cycles, turning point"},
{name:"Justice",num:"XI",suit:"major",meaning:"Balance, truth, fairness"},
{name:"The Hanged Man",num:"XII",suit:"major",meaning:"New perspective, sacrifice, surrender"},
{name:"Death",num:"XIII",suit:"major",meaning:"Transformation, endings, renewal"},
{name:"Temperance",num:"XIV",suit:"major",meaning:"Balance, moderation, patience"},
{name:"The Devil",num:"XV",suit:"major",meaning:"Bondage, materialism, shadow self"},
{name:"The Tower",num:"XVI",suit:"major",meaning:"Sudden upheaval, revelation, liberation"},
{name:"The Star",num:"XVII",suit:"major",meaning:"Hope, inspiration, serenity"},
{name:"The Moon",num:"XVIII",suit:"major",meaning:"Illusion, fear, subconscious"},
{name:"The Sun",num:"XIX",suit:"major",meaning:"Joy, success, vitality"},
{name:"Judgement",num:"XX",suit:"major",meaning:"Rebirth, inner calling, awakening"},
{name:"The World",num:"XXI",suit:"major",meaning:"Completion, achievement, wholeness"},
{name:"Ace of Wands",num:"A",suit:"wands",meaning:"Creative spark, new inspiration"},
{name:"Two of Wands",num:"2",suit:"wands",meaning:"Planning, future decisions"},
{name:"Three of Wands",num:"3",suit:"wands",meaning:"Progress, expansion, foresight"},
{name:"Four of Wands",num:"4",suit:"wands",meaning:"Celebration, home, harmony"},
{name:"Five of Wands",num:"5",suit:"wands",meaning:"Conflict, competition, tension"},
{name:"Six of Wands",num:"6",suit:"wands",meaning:"Victory, recognition, triumph"},
{name:"Seven of Wands",num:"7",suit:"wands",meaning:"Defense, perseverance, courage"},
{name:"Eight of Wands",num:"8",suit:"wands",meaning:"Speed, movement, rapid progress"},
{name:"Nine of Wands",num:"9",suit:"wands",meaning:"Resilience, persistence, last stand"},
{name:"Ten of Wands",num:"10",suit:"wands",meaning:"Burden, responsibility, hard work"},
{name:"Page of Wands",num:"P",suit:"wands",meaning:"Adventure, enthusiasm, exploration"},
{name:"Knight of Wands",num:"Kn",suit:"wands",meaning:"Energy, passion, bold action"},
{name:"Queen of Wands",num:"Q",suit:"wands",meaning:"Confidence, warmth, determination"},
{name:"King of Wands",num:"K",suit:"wands",meaning:"Vision, leadership, entrepreneurship"},
{name:"Ace of Cups",num:"A",suit:"cups",meaning:"New love, emotional awakening"},
{name:"Two of Cups",num:"2",suit:"cups",meaning:"Partnership, attraction, unity"},
{name:"Three of Cups",num:"3",suit:"cups",meaning:"Celebration, friendship, community"},
{name:"Four of Cups",num:"4",suit:"cups",meaning:"Contemplation, apathy, re-evaluation"},
{name:"Five of Cups",num:"5",suit:"cups",meaning:"Loss, grief, regret"},
{name:"Six of Cups",num:"6",suit:"cups",meaning:"Nostalgia, childhood, past memories"},
{name:"Seven of Cups",num:"7",suit:"cups",meaning:"Dreams, fantasy, wishful thinking"},
{name:"Eight of Cups",num:"8",suit:"cups",meaning:"Walking away, seeking deeper truth"},
{name:"Nine of Cups",num:"9",suit:"cups",meaning:"Contentment, wishes fulfilled"},
{name:"Ten of Cups",num:"10",suit:"cups",meaning:"Happiness, family, fulfillment"},
{name:"Page of Cups",num:"P",suit:"cups",meaning:"Creativity, intuition, new feelings"},
{name:"Knight of Cups",num:"Kn",suit:"cups",meaning:"Romance, charm, following the heart"},
{name:"Queen of Cups",num:"Q",suit:"cups",meaning:"Compassion, empathy, deep intuition"},
{name:"King of Cups",num:"K",suit:"cups",meaning:"Emotional balance, diplomacy, wisdom"},
{name:"Ace of Swords",num:"A",suit:"swords",meaning:"Clarity, truth, mental breakthrough"},
{name:"Two of Swords",num:"2",suit:"swords",meaning:"Indecision, stalemate, tough choice"},
{name:"Three of Swords",num:"3",suit:"swords",meaning:"Heartbreak, sorrow, painful truth"},
{name:"Four of Swords",num:"4",suit:"swords",meaning:"Rest, recovery, contemplation"},
{name:"Five of Swords",num:"5",suit:"swords",meaning:"Conflict, defeat, hollow victory"},
{name:"Six of Swords",num:"6",suit:"swords",meaning:"Transition, moving forward, healing"},
{name:"Seven of Swords",num:"7",suit:"swords",meaning:"Deception, strategy, stealth"},
{name:"Eight of Swords",num:"8",suit:"swords",meaning:"Feeling trapped, self-imposed limits"},
{name:"Nine of Swords",num:"9",suit:"swords",meaning:"Anxiety, nightmares, deep worry"},
{name:"Ten of Swords",num:"10",suit:"swords",meaning:"Painful ending, rock bottom, new dawn"},
{name:"Page of Swords",num:"P",suit:"swords",meaning:"Curiosity, vigilance, sharp mind"},
{name:"Knight of Swords",num:"Kn",suit:"swords",meaning:"Ambition, speed, decisive action"},
{name:"Queen of Swords",num:"Q",suit:"swords",meaning:"Independence, clear thinking, truth"},
{name:"King of Swords",num:"K",suit:"swords",meaning:"Authority, logic, intellectual power"},
{name:"Ace of Pentacles",num:"A",suit:"pentacles",meaning:"New opportunity, prosperity"},
{name:"Two of Pentacles",num:"2",suit:"pentacles",meaning:"Balance, adaptability, juggling"},
{name:"Three of Pentacles",num:"3",suit:"pentacles",meaning:"Teamwork, mastery, collaboration"},
{name:"Four of Pentacles",num:"4",suit:"pentacles",meaning:"Security, control, holding tight"},
{name:"Five of Pentacles",num:"5",suit:"pentacles",meaning:"Hardship, loss, feeling left out"},
{name:"Six of Pentacles",num:"6",suit:"pentacles",meaning:"Generosity, charity, sharing"},
{name:"Seven of Pentacles",num:"7",suit:"pentacles",meaning:"Patience, long-term investment"},
{name:"Eight of Pentacles",num:"8",suit:"pentacles",meaning:"Skill-building, diligence, craft"},
{name:"Nine of Pentacles",num:"9",suit:"pentacles",meaning:"Luxury, self-sufficiency, abundance"},
{name:"Ten of Pentacles",num:"10",suit:"pentacles",meaning:"Legacy, family wealth, tradition"},
{name:"Page of Pentacles",num:"P",suit:"pentacles",meaning:"Ambition, learning, new ventures"},
{name:"Knight of Pentacles",num:"Kn",suit:"pentacles",meaning:"Hard work, reliability, patience"},
{name:"Queen of Pentacles",num:"Q",suit:"pentacles",meaning:"Nurturing, practical abundance"},
{name:"King of Pentacles",num:"K",suit:"pentacles",meaning:"Wealth, business mastery, security"},
];
export const SUIT_INFO={major:"Major Arcana",wands:"Wands",cups:"Cups",swords:"Swords",pentacles:"Pentacles"};
